### PR TITLE
ID attribute begin with a number is not allowed at chrome.

### PR DESCRIPTION
**Pull request by inosphe**
Thank you for your carefulness. I made a mistake for the detail. And I also added some tests.

"Begin with a number (include numbers only)" ID attribute is not allowed at chrome.

like this
—
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#1671' is not a valid selector.
—

Fixed this issue.

### CODE REVIEW

**Comment by AvraamMavridis** [comment]
LGTM

**Comment by ronkorving** [comment]
LGTM

**Comment by brian-mann** [comment]
Here is jQuery's escape function.

Also apparently there is also `CSS.escape()` which also does what you're looking for.

- https://api.jquery.com/jQuery.escapeSelector/
- https://drafts.csswg.org/cssom/#the-css.escape()-method

**Comment by nickforddesign** [comment]
@brian-mann Just because it is technically possible doesn't mean it's very useful. Class names and IDs that disobey these rules cannot be selected with CSS, and other than the fact that sizzle and thus jQuery jump through hoops to support it, they are not easily accessible via the modern, standard JS DOM selection methods either. 

Might as well just omit them from the unique selector return value if they are going to be such a pain in the ass to use. I tested this very thoroughly, the return values are not any less unique if you omit these invalid selectors.

**Pull request closed without merging**
